// A stored conversation in the shape GET /v1/convai/conversations/{id} returns (trimmed from a real
// PoktaClinic call, fictional patient), plus fields the export must drop.
export const RAW_CONVERSATION = {
  conversation_id: "conv_test1",
  agent_id: "agent_x",
  agent_name: "pokta-clinic",
  version_id: "agtvrsn_1",
  branch_id: "agtbrch_1",
  status: "done",
  has_audio: true,
  user_id: "someone",
  metadata: {
    start_time_unix_secs: 1791474853,
    call_duration_secs: 60,
    main_language: "es",
    termination_reason: "end_call tool was called.",
    text_only: false,
    conversation_initiation_source: "react_sdk",
    timezone: "America/Mexico_City",
    charging: { tier: "creator" },
    cost: 3287,
  },
  conversation_initiation_client_data: { dynamic_variables: { caller_email: "private@example.com", system__conversation_history: "..." } },
  analysis: {
    call_successful: "success",
    call_summary_title: "Schedule First Consultation",
    transcript_summary: "The agent booked a visit.",
    evaluation_criteria_results: { consent_first: { criteria_id: "consent_first", result: "success", rationale: "Consent came first." } },
    data_collection_results: { consent_granted: { data_collection_id: "consent_granted", value: true, json_schema: { type: "boolean", description: "True if consent." }, rationale: "Said yes." } },
  },
  transcript: [
    { role: "agent", time_in_call_secs: 0, message: "[happy] Hola.", agent_metadata: { workflow_node_id: "consent" }, tool_calls: [], tool_results: [], interrupted: false },
    { role: "user", time_in_call_secs: 5, message: "Sí.", agent_metadata: null, tool_calls: [], tool_results: [], source_medium: "audio" },
    {
      role: "agent",
      time_in_call_secs: 10,
      message: null,
      agent_metadata: { workflow_node_id: "consent" },
      tool_calls: [
        {
          type: "webhook",
          request_id: "record_consent_1",
          tool_name: "record_consent",
          params_as_json: '{"granted": true}',
          tool_details: { method: "POST", url: "https://example.com/api/tools/record_consent?sig=abc", headers: { "x-pokta-tool-secret": "<REDACTED>" }, body: '{"conversation_id": "conv_test1", "granted": true}' },
        },
      ],
      tool_results: [],
    },
    { role: "agent", time_in_call_secs: 10, message: null, agent_metadata: { workflow_node_id: "consent" }, tool_calls: [], tool_results: [{ request_id: "record_consent_1", tool_name: "record_consent", type: "webhook", result_value: '{"ok":true,"granted":true}', is_error: false, tool_latency_secs: 0.25 }] },
    { role: "agent", time_in_call_secs: 12, message: null, agent_metadata: { workflow_node_id: "consent" }, tool_calls: [{ type: "workflow", request_id: "w1", tool_name: "notify_condition_2_met", params_as_json: "{}", tool_details: null }], tool_results: [] },
    {
      role: "agent",
      time_in_call_secs: 12,
      message: null,
      agent_metadata: { workflow_node_id: "consent" },
      tool_calls: [],
      tool_results: [{ request_id: "w1", tool_name: "notify_condition_2_met", type: "workflow", result_value: JSON.stringify({ steps: [{ type: "edge", edge_id: "consent_to_identification", target_node_id: "identification" }, { type: "nested_tools", requests: [] }] }), is_error: false, tool_latency_secs: 0.007 }],
    },
    { role: "agent", time_in_call_secs: 13, message: "¿Su teléfono?", agent_metadata: { workflow_node_id: "identification" }, tool_calls: [], tool_results: [] },
    { role: "agent", time_in_call_secs: 20, message: null, agent_metadata: { workflow_node_id: "identification" }, tool_calls: [{ type: "webhook", request_id: "save_1", tool_name: "save_patient", params_as_json: '{"nombre":"Lucía"}', tool_details: { method: "POST", url: "https://example.com/api/tools/save_patient", body: "{}" } }], tool_results: [] },
    { role: "agent", time_in_call_secs: 21, message: null, agent_metadata: { workflow_node_id: "identification" }, tool_calls: [], tool_results: [{ request_id: "save_1", tool_name: "save_patient", type: "webhook", result_value: '{"ok":true,"patient_id":"9dc20b62-37a4-4e0a-8a2f-0bae93fbe9ce","folio":"EXP-1","given_name":"Lucía","already_registered":false,"api_token":"leak"}', is_error: false, tool_latency_secs: 0.4 }] },
  ],
};
